spring:
 jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         show_sql: true
         dialect: org.hibernate.dialect.MySQL57Dialect
         format_sql: true
         use_sql_comments: true
 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc_o2o?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sqlpass